=head1 Mo Features

Mo is absoutely minimal, but it let's you easily add many features like this:

    use Mo qw[default builder other features];

This will load the modules L<Mo::default>, etc, and have them modify your Mo
reality.

Here's a list of the current feature modules:

=over

=item * L<Mo::default> - Add C<default> feature to C<has>.

=item * L<Mo::builder> - Add C<builder> feature to C<has>.

=item * L<Mo::coerce> - Add C<coerce> feature to C<has>.

=item * L<Mo::is> - Add C<is> feature to C<has>.

=item * L<Mo::required> - Add C<required> feature to C<has>.

=back

=head1 NOTE

Don't assume that all feature modules will work together. Sometimes the order
you specify them in may affect how they work together. Read the feature docs
and test you assumptions.
