=encoding utf8

=head1 Name

Mo::builder - adds the builder and default features to Mo's has

=head1 Synopsis

    use Mo qw'has';
    has name1 => ( default => sub { 'Joe' } );
    has name2 => ( builder => 'name_lookup' );

=head1 Description

Loads the features L<Mo::builder> and L<Mo:default>.

NOTE: This feature is likely to undergo a lot of changes. Beware.

=cut
